### ISSUE TITLE
spatial clean on windows fails in cmd and powershell

### ISSUE THREAD

**Issue by polartron** [spatialos/UnityGDK#52]
#### Description
Running spatial clean in cmd or powershell on windows outputs an error because it can't find the program "rm"

## Expected behaviour
spatial clean should function without issues on windows without using git-bash

## Current behaviour

> Running task 'clean' for 'UnityClient'
[1/1] > Clean Codegen
[1/1] x Clean Codegen (10ms)
error: exec: "rm": executable file not found in %PATH%
failed (10ms)
'spatial clean' failed (0.0s)
Encountered an error during command execution.
    exit status 1

## Steps to reproduce

1. Open up a Windows Powershell or cmd in the UnityGDK directory
2. Run spatial clean

## Environment

> PS C:\Unity Projects\UnityGDK> spatial diagnose
> Microsoft Visual C++ (MSVC) Redistributable
>  [SUCCESS]
>  - Found version 14.12.25810.
> Network access
>  [SUCCESS]
>  - All checks passed
>  - Installed at 'C:\Users\TRON\.improbable\spatial\spatial.exe'.
>P roject's SpatialOS SDK
>  [SUCCESS]
>  - Found version 13.0.1.
> Spatial CLI SDK plugin
>  [SUCCESS]
>  - Installed at 'C:\Users\TRON\AppData\Local\.improbable\bin\plugins\sdk\13.0.1\sdk.exe'.
>  - Found version 13.0.1.
> Spatial CLI tool
>  [SUCCESS]
>  - Installed at 'C:\Users\TRON\.improbable\spatial\spatial.exe'.
>  - Found version 20180628.171450.

>Results
>  All diagnostic checks passed successfully.
>'spatial diagnose' succeeded (8.2s)

**Comment by oblm** [comment]
Thanks for your detailed report @polartron. This is our first external GDK issue report and we're disproportionately excited about it. We're tracking it internally as UTY-576.
### Acceptance Criteria:
* Running `spatial clean` inside a SpatialOS project on windows succeeds in cmd, PowerShell and Git BASH.
* Audit or lint for instances where aliases (such as `rm` instead of `remove-item`, are used).

**Comment by oblm** [comment]
Hey @polartron,

We've redesigned the Unity GDK workflow so that, rather than use `spatial clean` and `spatial build`, all build processes are now achieved by the scripts in [/ci](https://github.com/spatialos/UnityGDK/tree/master/ci). As such this ticket is now redundant, as you'll never have to `spatial clean` in a GDK project again.

If you have a use case for a  `spatial clean`-like command, do let us know.

We'll be documenting the scripts  in [/ci](https://github.com/spatialos/UnityGDK/tree/master/ci), and the workflows we envision they'll be used in, in the very near future.
